# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
quadprog_solveC2 <- function(Dmat, dvec, At) {
    .Call('_MALT_quadprog_solveC2', PACKAGE = 'MALT', Dmat, dvec, At)
}

#'@export
quadprog_solveC1 <- function(Dmat, dvec, At, Bt) {
    .Call('_MALT_quadprog_solveC1', PACKAGE = 'MALT', Dmat, dvec, At, Bt)
}

#'@export
quadprog_solveC <- function(Dmat, dvec, At) {
    .Call('_MALT_quadprog_solveC', PACKAGE = 'MALT', Dmat, dvec, At)
}

#'@export
logPL_C <- function(X, indset, cen, beta) {
    .Call('_MALT_logPL_C', PACKAGE = 'MALT', X, indset, cen, beta)
}

#'@export
val_pen <- function(Apo, w, nb, m, beta) {
    .Call('_MALT_val_pen', PACKAGE = 'MALT', Apo, w, nb, m, beta)
}

#'@export
roundvec <- function(beta, eps) {
    .Call('_MALT_roundvec', PACKAGE = 'MALT', beta, eps)
}

lasso_tree_single <- function(X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace, fullA = FALSE) {
    .Call('_MALT_lasso_tree_single', PACKAGE = 'MALT', X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace, fullA)
}

lasso_tree_multi <- function(X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace) {
    .Call('_MALT_lasso_tree_multi', PACKAGE = 'MALT', X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace)
}

